apiVersion: v1
kind: ConfigMap
metadata:
  name: wkadd-config
  labels:
    app: wkadd
data:
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.Hosting.Lifetime: "Information"  
  RabbitMQ__Exchange: "Fase3.Contatos.Add"
  RabbitMQ__QueueName: "Fase3.Contatos.AddtoDataBase"
  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: apipostech-deployment-add
  labels:
    app: apipostechadd
spec:
  replicas: 2  # Número de réplicas desejadas
  selector:
    matchLabels:
      app: apipostechadd  

  template:
    metadata:
      labels:
        app: apipostechadd  # Label aplicada aos pods        
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: apipostechadd
        image: postech-add:1.2
        ports:
        - containerPort: 8080  
        envFrom:
        - configMapRef:
            name: wkadd-config
        - configMapRef:
            name: rabbitmq-shared-config
        - configMapRef:
            name: database-shared-config    