apiVersion: v1
kind: ConfigMap
metadata:
  name: apipostech-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"  
  RabbitMQ__ExchangeAdd: "Fase3.Contatos.Add"
  RabbitMQ__ExchangeUpdate: "Fase3.Contatos.Update"
  RabbitMQ__ExchangeDelete: "Fase3.Contatos.Delete"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: apipostech-deployment
  labels:
    app: apipostech
spec:
  replicas: 2  # Número de réplicas desejadas
  selector:
    matchLabels:
      app: apipostech  # Seleciona os pods com esta label
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
      labels:
        app: apipostech  # Label aplicada aos pods
    spec:
      containers:
      - name: apipostech
        image: postech-contatos:1.0 
        ports:
        - containerPort: 8080  
        envFrom:
        - configMapRef:
            name: apipostech-config
        - configMapRef:
            name: rabbitmq-shared-config
        - configMapRef:
            name: database-shared-config

--- 
apiVersion: v1
kind: Service
metadata:
  name: apipostech-service
  labels:
    app: apipostech
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 8043
      targetPort: 8081
      protocol: TCP
      name: https
  selector:
    app: apipostech
